spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:public}

  liquibase:
    # clear-checksums: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    defaultSchema: ${DB_SCHEMA:public}
    liquibaseSchema: ${DB_SCHEMA:public}

server:
  port: 8090
  servlet:
    context-path: /api

logging:
  level:
    root: info

account:
  number:
    batch.size: 10
    schedule:
      personal-checking: "0 0 0 * * *"
      business-checking: "0 0 0 * * *"
      savings: "0 0 0 2 * *"
      currency: "0 0 0 14 * *"
      deposit: "0 0 0 5 * *"
    prefix:
      personal-checking: 4200000000000000
      business-checking: 4300000000000000
      savings: 5236000000000000
      currency: 5500000000000000
      deposit: 6500000000000000